start.sublime-snippet
Update start command to match current AWS template anatomy:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
=> Match current template anatomy.

route53-hostedzone.sublime-snippet, route53-recordset-group.sublime-snippet, route53-recordset.sublime-snippet
CloudFormation Route53 resources:
* AWS::Route53::HostedZone - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html
* AWS::Route53::RecordSet - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
* AWS::Route53::RecordSetGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordsetgroup.html
=> Route53 Cloud Formation Syntax

s3-bucket.sublime-snippet, s3-bucketpolicy.sublime-snippet
CloudFormation S3 Bucket and S3 Bucket Policy from:
* http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
* http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html
=> S3 bucket Cloud Formation Syntax

sqs-queue.sublime-snippet, sqs-queuepolicy.sublime-snippet
CloudFormation SQS resources:
* AWS::SQS::Queue - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
* AWS::SQS::QueuePolicy - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-policy.html
=> Simple Queue Service Cloud Formation Syntax

sns-topic.sublime-snippet, sns-topicpolicy.sublime-snippet
CloudFormation SNS resources:
* AWS::SNS::Topic - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html
* AWS::SNS::TopicPolicy - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-policy.html
=> Simple Notification Service Cloud Formation Syntax

cloudtrail.sublime-snippet
CloudFormation CloudTrail resources:
* AWS::CloudTrail::Trail - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html
=> CloudTrail Cloud Formation Syntax

cloudwatch-alarm.sublime-snippet
CloudFormation CloudWatch Alarm resources:
* AWS::CloudWatch::Alarm - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
=> CloudWatch Alarm Cloud Formation Syntax

iam-accesskey.sublime-snippet, iam-group.sublime-snippet, iam-instanceprofile.sublime-snippet, iam-policy.sublime-snippet, iam-role.sublime-snippet, iam-user.sublime-snippet, iam-usertogroupaddition.sublime-snippet
CloudFormation IAM resources:
* AWS::IAM::AccessKey - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html
* AWS::IAM::Group - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-group.html
* AWS::IAM::InstanceProfile - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html
* AWS::IAM::Policy - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
* AWS::IAM::Role - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
* AWS::IAM::User - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html
* AWS::IAM::UserToGroupAddition - …
=> IAM Cloud Formation Syntax

rds-dbinstance.sublime-snippet, rds-dbparametergroup.sublime-snippet, rds-dbsecuritygroup.sublime-snippet, rds-dbsecuritygroupingress.sublime-snippet, rds-dbsubnetgroup.sublime-snippet, rds-eventsubscription.sublime-snippet
CloudFormation RDS resources:
* AWS::RDS::DBInstance - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
* AWS::RDS::DBParameterGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbparametergroup.html
* AWS::RDS::DBSubnetGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbsubnet-group.html
* AWS::RDS::DBSecurityGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-security-group.html
* AWS::RDS::DBSecurityGroupIngress - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-security-group-ingress.html
* AWS::RDS::EventSubscription - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resourc …
=> Relational Database Service Cloud Formation Syntax

redshift-cluster.sublime-snippet, redshift-clusterparametergroup.sublime-snippet, redshift-clustersecuritygroup.sublime-snippet, redshift-clustersecuritygroupingress.sublime-snippet, redshift-clustersubnetgroup.sublime-snippet
CloudFormation RedShift resources:
* AWS::Redshift::Cluster - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html
* AWS::Redshift::ClusterParameterGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-clusterparametergroup.html
* AWS::Redshift::ClusterSecurityGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-clustersecuritygroup.html
* AWS::Redshift::ClusterSecurityGroupIngress - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-clustersecuritygroupingress.html
* AWS::Redshift::ClusterSubnetGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-clustersubnetgroup.html
=> RedShift Cloud Formation Syntax

opsworks-app.sublime-snippet, opsworks-elasticloadbalancerattachment.sublime-snippet, opsworks-instance.sublime-snippet, opsworks-layer.sublime-snippet, opsworks-stack.sublime-snippet
CloudFormation OpsWorks resources:
* AWS::OpsWorks::App - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-app.html
* AWS::OpsWorks::ElasticLoadBalancerAttachment - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-elbattachment.html
* AWS::OpsWorks::Instance - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-instance.html
* AWS::OpsWorks::Layer - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-layer.html
* AWS::OpsWorks::Stack - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-stack.html
=> OpsWorks Cloud Formation Syntax

elasticache-cachecluster.sublime-snippet, elasticache-parametergroup.sublime-snippet, elasticache-securitygroup.sublime-snippet, elasticache-securitygroupingress.sublime-snippet, elasticache-subnetgroup.sublime-snippet
CloudFormation ElastiCache resources:
* AWS::ElastiCache::CacheCluster - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html
* AWS::ElastiCache::ParameterGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-parameter-group.html
* AWS::ElastiCache::SecurityGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-security-group.html
* AWS::ElastiCache::SecurityGroupIngress - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-security-group-ingress.html
* AWS::ElastiCache::SubnetGroup - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-subnetgroup.html
=> ElastiCache Cloud Formation Syntax

elasticbeanstalk-application.sublime-snippet, elasticbeanstalk-applicationversion.sublime-snippet, elasticbeanstalk-configurationtemplate.sublime-snippet, elasticbeanstalk-environment.sublime-snippet
CloudFormation Elastic Bean Stalk resources:
* AWS::ElasticBeanstalk::Application - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk.html
* AWS::ElasticBeanstalk::ApplicationVersion - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-version.html
* AWS::ElasticBeanstalk::ConfigurationTemplate - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-beanstalk-configurationtemplate.html
* AWS::ElasticBeanstalk::Environment - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment.html
=> Elastic Bean Stalk Cloud Formation Syntax

kinesis-stream.sublime-snippet
CloudFormation Kinesis resources:
* AWS::Kinesis::Stream - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html
=> Kinesis Stream Cloud Formation Syntax

route53-healthcheck.sublime-snippet
* AWS::Route53::HealthCheck - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-healthcheck.html
=> Added Route53 HealthCheck Syntax

dynamodb-table.sublime-snippet
CloudFormation DynamoDB Table resource:
* AWS::DynamoDB::Table - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
=> DynamoDB Table Cloud Formation Syntax

cloudfront-distribution.sublime-snippet
CloudFormation CloudFront resource:
* AWS::CloudFront::Distribution - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution.html
=> Cloud Front Distribution Cloud Formation Syntax

parameter-type-availabilityzone-name-list.sublime-snippet, parameter-type-availabilityzone-name.sublime-snippet, parameter-type-ec2-image-id-list.sublime-snippet, parameter-type-ec2-image-id.sublime-snippet, parameter-type-ec2-instance-id-list.sublime-snippet, parameter-type-ec2-instance-id.sublime-snippet, parameter-type-ec2-security-group-name-list.sublime-snippet, parameter-type-ec2-security-group-name.sublime-snippet, parameter-type-ec2-volume-id-list.sublime-snippet, parameter-type-ec2-volume-id.sublime-snippet, parameter-type-keypair-keyname.sublime-snippet, parameter-type-keypair.sublime-snippet, parameter-type-route53-hostedzone-id-list.sublime-snippet, parameter-type-route53-hostedzone-id.sublime-snippet, parameter-type-securitygroup-id-list.sublime-snippet, parameter-type-securitygroup-id.sublime-snippet, parameter-type-subnet-id-list.sublime-snippet, parameter-type-subnet-id.sublime-snippet, parameter-type-vpc-id-list.sublime-snippet, parameter-type-vpc-id.sublime-snippet
To be used within the quotes of parameter Type field
=> Add Param types

cloudformation-authentication.sublime-snippet, cloudformation-customresource.sublime-snippet, cloudformation-init.sublime-snippet, cloudformation-stack.sublime-snippet, cloudformation-waitcondition.sublime-snippet, cloudformation-waitconditionhandle.sublime-snippet
CloudFormation CloudFormation resources:
* AWS::CloudFormation::Authentication - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-authentication.html
* AWS::CloudFormation::CustomResource - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html
* AWS::CloudFormation::Init - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html
* AWS::CloudFormation::Stack - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html
* AWS::CloudFormation::WaitCondition - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html
* AWS::CloudFormation::WaitConditionHandle - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-prope …
=> CloudFormation CloudFormation Syntax

ec2-volume.sublime-snippet
CloudFormation EC2 EBS volume support:
* AWS::EC2::Volume
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html
=> Snippet for EC2 volume resource
